
spring:
  application:
    name: TaskManagement

  datasource:
    url: jdbc:postgresql://dpg-cv4hijij1k6c73bk3v80-a:5432/taskmanagement_db_2x78
    username: taskmanagement_db_2x78_user
    password: faNkzIPeN0hV09jORClzoEevQMaqr0WC
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


app:
  security:
    key:
      signingSecret: 1qaz:0okm:4rfv:7ujm:6tfc::123edc:8uhb
      type: shared
    jwt:
      atExpirationMin: 360
      rtExpirationMin: 4320
      authType: Bearer
      header: Authorization
      issuer: https://neha-task-management.in
