spring.application.name=TaskManagement

spring.datasource.url=jdbc:mysql://localhost:3306/Task

spring.datasource.username=root

spring.datasource.password= Ashar@581

spring.jpa.hibernate.ddl-auto=update